package com.example.lykkehjul

object WordsMemoryDB
{
    val dkCities: List<String> =
        listOf(
            "Taastrup",
            "Esbjerg",
            "Roskilde",
            "Herning",
            "Glostrup",
            "Aabenraa",
            "Kolding",
            "Vordingborg",
            "Hundested",
            "Kokkedal",
            "Middelfart",
            "Holstebro",
            "Odense",
            "Charlottenlund",
            "Farum",
            "Allinge",
            "Ballerup",
            "Billund",
            "Bogense",
            "Frederiksberg",
            "Fredericia",
            "Frederikssund",
            "Faaborg",
            "Gedser",
            "Gentofte",
            "Hellerup",
            "Herlev",
            "Kalundborg",
            "Karlslunde",
            "Lunderskov",
            "Ringsted",
            "Skagen",
            "Skanderborg",
            "Skovlunde",
            "Thisted",
            "Vejen",
            "Lyngby"
        )

    val capitals: List<String> =
        listOf(
            "Copenhagen",
            "Stockholm",
            "Olso",
            "London",
            "Paris",
            "Amsterdam",
            "Cardiff",
            "Moscow",
            "Tokyo",
            "Dublin",
            "Ottawa",
            "Tallinn",
            "Helsinki",
            "Reykjavik",
            "Athens",
            "Warszaw",
            "Lisbon",
            "Bucharest",
            "Berlin",
            "Kabul",
            "Canberra",
            "Vienna",
            "Baku",
            "Brussels",
            "Minsk",
            "Basilia",
            "Sofia",
            "Santiago",
            "Beijing",
            "Zagreb",
            "Prague",
            "Cairo",
            "Budapest",
            "Baghdad",
            "Jakarta",
            "Jerusalem",
            "Rome",
            "Riga",
            "Rabat",
            "Kathmandu",
            "Wellington",
            "Pyongyang",
            "Islamabad",
            "Lima",
            "Manila",
            "Doha",
            "Seoul",
            "Madrid",
            "Bangkok",
            "Taipei",
            "Bern",
            "Ankara"
        )

    val usStates: List<String> =
        listOf(
            "Alabama",
            "Alaska",
            "Arizona",
            "Arkansas",
            "California",
            "Colorado",
            "Connecticut",
            "Delaware",
            "Florida",
            "Georgia",
            "Hawaii",
            "Idaho",
            "Illinois",
            "Indiana",
            "Iowa",
            "Kansas",
            "Kentucky",
            "Louisiana",
            "Maine",
            "Maryland",
            "Massachusetts",
            "Michigan",
            "Minnesota",
            "Mississippi",
            "Missouri",
            "Montana",
            "Nebraska",
            "Nevada",
            "New Hampshire",
            "New Jersey",
            "New Mexico",
            "New York",
            "North Carolina",
            "North Dakota",
            "Ohio",
            "Oklahoma",
            "Oregon",
            "Pennsylvania",
            "Rhode Island",
            "South Carolina",
            "South Dakota",
            "Tennessee",
            "Texas",
            "Utah",
            "Vermont",
            "Virginia",
            "Washington",
            "West Virginia",
            "Wisconsin",
            "Wyoming"
        )

    val mixedAnimals: List<String> =
        listOf(
            "Elephant",
            "Penguin",
            "Hippopotamus",
            "Tiger",
            "Leopard",
            "Kangaroo",
            "Giraffe",
            "Panda",
            "Hedgehog",
            "Crocodile",
            "Cheetah",
            "Spider",
            "Bumblebee",
            "Bear",
            "Lion",
            "Fish",
            "Horse",
            "Camel",
            "Wolf",
            "Fennec",
            "Goat",
            "Butterfly",
            "Frog",
            "Snail",
            "Scorpion",
            "Ladybug",
            "Mouse",
            "Zebra",
            "Moose",
            "Panda",
            "Rabbit",
            "Hamster",
            "Raccoon",
            "Antelope",
            "Sheep"
        )
    val birds: List<String> =
        listOf(
            "Peacock",
            "Chicken",
            "Eagle",
            "Robin",
            "Blackbird",
            "Woodpecker",
            "Flamingo",
            "Ostrich",
            "Pelican",
            "Duck",
            "Hummingbird",
            "Kiwi",
            "Stork",
            "Pigeon",
            "Vulture",
            "Falcon",
            "Turkey",
            "Albatross",
            "Parrot",
            "Seagull",
            "Swan"
        )

    val waterAnimals: List<String> =
        listOf(
            "Jellyfish",
            "Shark",
            "Clownfish",
            "Hammerhead",
            "Dolphin",
            "Octopus",
            "Catfish",
            "Crab",
            "Seal",
            "Whale",
            "Shrimp",
            "Tuna",
            "Seahorse",
            "Turtle",
            "Starfish",
            "Oyster",
            "Goldfish",
            "Walrus",
            "Orca",
            "Lobster",
            "Piranha",
            "Eel"
        )

    val marvelCharacters: List<String> =
        listOf(
            "Spiderman",
            "Hawkeye",
            "Mantis",
            "Hulk",
            "Wolverine",
            "Elektra",
            "Beast",
            "Quake",
            "Deadpool",
            "Venom",
            "Polaris",
            "Mystique",
            "Daredevil",
            "Punisher",
            "Gamora",
            "Wasp",
            "Taskmaster",
            "Vision",
            "Nebula",
            "Stature",
            "Groot",
            "Yellowjacket",
            "Yondu",
            "Falcon",
            "Drax",
            "Magneto",
            "Thanos",
            "Phoenix",
            "Black Widow",
            "Captain America",
            "Iron Man",
            "Ultron",
            "Scarlet Witch",
            "Black Panther",
            "Thor",
            "Doctor Strange",
            "Silver Surfer",
            "Ghost Rider",
        )
    val harryPotter: List<String> =
        listOf(
            "Weasley",
            "Hermione",
            "Quidditch",
            "Wand",
            "Hogwarts",
            "Hufflepuff",
            "Gryffindor",
            "Slytherin",
            "Ravenclaw",
            "Voldemort",
            "Dobby",
            "Accio",
            "Alohomora",
            "Expelliarmus",
            "Lumos",
            "Azkaban",
            "Hippogriff",
            "Polyjuice",
            "Patronus",
            "Animagus",
            "Bellatrix",
            "Dumbledore",
            "McGonagall",
            "Boggart",
            "Muggle",
            "Galleon",
            "Auror",
            "Basilisk",
            "Butterbeer",
            "Dementor",
            "Dragon",
            "Durmstrang",
            "Gillyweed",
            "Goblins",
            "Gringotts",
            "Hogsmeade",
            "Howler",
            "Metamorphmagus",
            "Mudblood",
            "Niffler",
            "Parselmouth",
            "Phoenix",
            "Portkey",
            "Potion",
            "Charm",
            "Time turner",
            "Sorting hat"
        )

    val vegetables : List<String> =
        listOf("Carrot",
            "Cucumber",
            "Eggplant",
            "Onion",
            "Garlic",
            "Cabbage",
            "Radish",
            "Mushroom",
            "Broccoli",
            "Lettuce",
            "Celery",
            "Beetroot",
            "Cauliflower",
            "Pumpkin",
            "Radish",
            "Asparagus",
            "Olive",
            "Celery",
            "Potato",
            "Bell Pepper",
            "Corn")

    val fruits : List<String> =
        listOf("Apple",
            "Banana",
            "Pear",
            "Watermelon",
            "Plum",
            "Lime",
            "Raspberry",
            "Blueberry",
            "Strawberry",
            "Pineapple",
            "Orange",
            "Grape",
            "Clementine", "Redberries", "Dragonfruit", "Passionfruit", "Cranberry", "Grapefruit", "Kiwi", )

    val holidays : List<String> =
        listOf("Christmas",
            "Easter",
            "Thanksgiving",
            "Valentines Day",
            "Halloween",
            "Chinese New Year",
            "Saint Patricks Day",
            "Independence Day",
            "Hanukkah",
            "Ramadan",
            "New Years Eve",
            "Epiphany Day",
            "Labor Day",
            "Diwali",
            "Bodhi Day",
            "Groundhog Day",
            "Yom Kippur"
        )

    val space : List <String> =
        listOf("Solar System",
            "Sun",
            "Moon",
            "Earth",
            "Jupiter",
            "Mercury",
            "Neptune",
            "Uranus",
            "Venus",
            "Mars",
            "Saturn",
            "Asteroid",
            "Astronaut",
            "Stars",
            "Milkyway",
            "Galaxy",
            "Super Nova",
            "Meteor",
            "Satellite",
            "Meteorite",
            "Telescope",
            "Planet",
            "NASA")

    val wordList =
        listOf (dkCities.random(),
            capitals.random(),
            usStates.random(),
            mixedAnimals.random(),
            birds.random(),
            waterAnimals.random(),
            marvelCharacters.random(),
            harryPotter.random(),
            fruits.random(),
            vegetables.random(),
            holidays.random(),
            space.random()
        ).random()

    val testData =
        listOf("test", "abcde")

    val categoryList : List <String> =
        listOf("Danish City",
        "Capital",
        "US States",
        "Animal",
        "Bird",
        "Water Animal",
        "Marvel Character",
        "Harry Potter",
        "Fruit",
        "Vegetables",
        "Holiday",
        "Space")
}
